= Bock Buckets
include::./_header/main-header.txt[]
:stylesdir: ./_stylesheet
:toclevels: 2

[discrete]
===== xref:README.adoc[🡄 Return to the index]

== Introduction

Block buckets allow you to specify however many blocks you want, for every component of a plot. You can specify the block weight, which will determine how likely the block is to be picked from the bucket.

* `stone,grass_block,cobblestone,sandstone` will automatically infer that there should be 25% of each of the four blocks
* `stone:50,grass_block:30,sandstone:20` will use 50% of stone, 30% of grass_block and 20% of sandstone.

== Formatting

Blocks can be in the format `namespace:block[property1=value1,property2=value2]` (The properties and namespace are optional, and `grass_block` will resolve to `minecraft:grass_block[snowy=false]`. https://minecraft.gamepedia.com/Block_states[More info])

Complex patterns are also accepted:

* https://intellectualsites.github.io/fastasyncworldedit-documentation/patterns/patterns[FAWE Patterns] (If you have FAWE installed)
// TODO Find proper Fawe link
* https://worldedit.enginehub.org/en/latest/usage/general/patterns/[WorldEdit Patterns]

== Disallowed Blocks

To restrict what blocks are allowed for the patterns, configure the `disallowed-blocks` list in `plugins/WorldEdit/config.yml`, or `plugins/FastAsyncWorldEdit/worldedit-config.yml`
