= Placeholders
include::../_header/main-header.txt[]
:stylesdir: ../_stylesheet
:toclevels: 2

[discrete]
===== xref:../README.adoc[🡄 Return to the index]

== Introduction

[NOTE]
The placeholder integration allows you to display data from other plugins in specific locations in PlotSquared.

For example, with https://www.spigotmc.org/resources/featherboard.2691[FeatherBoard] you can create a scoreboard (sideboard) with the info about the plot you're standing on. And with using https://www.spigotmc.org/resources/placeholderapi.6245/[PlaceholderAPI], you can do `/plot flag set greeting Welcome %player_name%` which translates to "Welcome Steve" when the player Steve enters a plot. +
The `Player` expansion from PlaceholderAPI is required to be installed.

Currently, (FeatherBoard and) PlaceholderAPI placeholders, can be used in the `greeting` and `farewell` flag of a plot.

== Setup

PlotSquared has explicit and official support for https://www.spigotmc.org/resources/placeholderapi.6245/[*PlaceholderAPI*] and https://www.spigotmc.org/resources/mvdwplaceholderapi.11182/[*MVdWPlaceholderAPI*].

Follow the instruction of these placeholder systems to install it correctly.

[NOTE]
For the PlaceholderAPI placeholders of PlotSquared you don't need to download a PAPI expansion. As opposed to some other plugins, PlotSquared handles everything internally.

== Placeholder Deactivation in PlotSquared

Placeholders can be turned off in `settings.yml`:

[source]
----
  external-placeholders: false
----

== Tips for specific plugins

=== Chat-System

If you're using *EssentialsChat* and *PlaceholderAPI*, you must install https://www.spigotmc.org/resources/chatinjector.38327/[*ChatInjector*] in order for the placeholders to show up in the chat. However, please note it has been reported that ChatInjector might cause issues.

== PlotSquared placeholders

[TIP]
If you think a placeholder for PlotSquared should be added, then please https://github.com/IntellectualSites/PlotSquared/issues/new/choose[raise an issue here].

_Available placeholders in 6.0.0 onwards:_

|===
| Placeholder | Description

| `%plotsquared_currentplot_alias%`
| Alias of the plot

| `%plotsquared_currentplot_owner%`
| Owner of the plot

| `%plotsquared_currentplot_members%`
| Amount of players added and trusted to the plot

| `%plotsquared_currentplot_members_added%`
| Amount of players added to the plot

| `%plotsquared_currentplot_members_added_list%`
| Display a list of added members

| `%plotsquared_currentplot_members_trusted%`
| Amount of players trusted to the plot

| `%plotsquared_currentplot_members_trusted_list%`
| Display a list of trusted members

| `%plotsquared_currentplot_members_denied%`
| Amount of members denied from the plot

| `%plotsquared_currentplot_members_denied_list%`
| Display a list of denied members

| `%plotsquared_currentplot_world_name%`
| Get the world name

| `%plotsquared_currentplot_can_build%`
| Displays true or false whether the player has build rights on the plot

| `%plotsquared_world_name%`
| Get the name of the world

| `%plotsquared_has_plot%`
| Displays true or false whether the player has plot

| `%plotsquared_has_plot_(world)%`
| Displays true or false whether the player has plot in a specific world

| `%plotsquared_plot_count%`
| Amount of global plots of a player

| `%plotsquared_plot_count_(World)%`
| Amount of plots for a player in a specific world

| `%plotsquared_allowed_plot_count%`
| Amount of maximum plots a player can have. Returns "infinite" if you have * permission

| `%plotsquared_currentplot_xy%`
| Displays the X and Y ID of a plot

| `%plotsquared_currentplot_x%`
| Displays the X ID of a plot

| `%plotsquared_currentplot_y%`
| Displays the Y ID of a plot

| `%plotsquared_currentplot_rating%`
| Displays the average rating of a plot

| `%plotsquared_currentplot_biome%`
| Displays the biome of a plot

| `%plotsquared_currentplot_localflag_<flag>%`
| Display the value of the flag set on current plot

| `%plotsquared_currentplot_flag_<flag>%`
| Display the value of the flag set on current plot or if it's not set: display the inherited flag value (worlds.yml)

| `%plotsquared_currentplot_creationdate%`
| Display the creation date of the plot
|===

== External placeholders

=== PlaceholderAPI placeholders

https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders

=== MVdWPlaceholderAPI placeholders

https://www.spigotmc.org/wiki/mvdw-placeholders
