name: generate-wiki
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@9527ff583929b1000c23c209123bba4e98a21f08 # v2
        with:
          asciidoctor_params: --attribute=nofooter
          pdf_build: true
          source_dir: sources/
          slides_build: true
          slides_main_adoc_file: README
